### ISSUE TITLE
Document `technology_bridge.csv`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.scenario.preparation#12]
Flag an issue to document format for this file.

_Originally posted by @AlexAxthelm in https://github.com/RMI-PACTA/workflow.scenario.preparation/pull/11#discussion_r1495859805_

**Comment by cjyetman** [comment]
use of the `technology_bridge.csv` was removed in #22 

will update README

**Comment by jdhoffa** [comment]
Shall we close this then?
