### ISSUE TITLE
Improve error handling across `workflow.*` and `pacta.*` 

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.scenario.preparation#13]
My thoughts right now are that:
`rlang::warning` and `rlang::abort` should exist at the level of the exported R package function

and `logger::` type messages should pertain mainly to the file i/o/ anything Dockerized. 

              Suggest throwing an error as well as the log message.

Or alternately `log_warn()` and `warning()`

_Originally posted by @AlexAxthelm in https://github.com/RMI-PACTA/workflow.scenario.preparation/pull/11#discussion_r1495866442_
            

[AB#9950](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/9950)

**Comment by AlexAxthelm** [comment]
I'm generally on board with that.

**Comment by cjyetman** [comment]
Can we find a better place to host these meta issues that pertain to multiple repos? I feel like as an issue in a specific repo, it makes the issue itself basically unachievable, so it's likely to just sit here forever?

**Comment by jdhoffa** [comment]
Yup, do you have any ideas?

**Comment by jdhoffa** [comment]
I can make an ADO ticket somewhere
