### ISSUE TITLE
Implement new docker build action

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.scenario.preparation#14]
All I can do really is very cautiously approve this, and likely try to test the action in the wild on a relevant repo!

_Originally posted by @jdhoffa in https://github.com/RMI-PACTA/actions/pull/56#pullrequestreview-1890868263_
            

[AB#9930](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/9930)

**Comment by AlexAxthelm** [comment]
FYI, I'll be adding the actions to workflow.pacta (https://github.com/RMI-PACTA/workflow.factset/issues/54) soon. I'll let you know how that goes.

**Comment by jdhoffa** [comment]
@AlexAxthelm I believe you are building a much broader Action that takes care of everything. Is this issue still relevant?

**Comment by AlexAxthelm** [comment]
Still relevant. have a couple of housekeeping things to take care of in that action, but it's available for use as part of https://github.com/RMI-PACTA/actions/blob/main/.github/workflows/docker.yml.

The big that's missing compared to previous workflows we've used is that it doesn't add a comment to PRs.

**Comment by jdhoffa** [comment]
Sounds good!

**Comment by AlexAxthelm** [comment]
Partially resolved in #36. full resolution depends on https://github.com/RMI-PACTA/actions/issues/58

**Comment by cjyetman** [comment]
I'm gonna call this closed by #36, and I opened a new issue for using the platform specification once it's ready in #45
