### ISSUE TITLE
2022Q4 Scenario prep exits with warnings

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/workflow.scenario.preparation#43]
From a recent run of 2022Q4 Scenario prep:
```
Warning message:
One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat) 
INFO [2024-04-16 10:16:33] Finished processing scenarios.
```

likely relates to https://github.com/RMI-PACTA/pacta.scenario.data.preparation/pull/29#issuecomment-2049287776

**Comment by cjyetman** [comment]
also relevant ticket on private ADO is here https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/10608
though it's "Done", so probably a new related ticket needs to be opened (but the necessary details are there) @jdhoffa

**Comment by cjyetman** [comment]
@AlexAxthelm for detail...

In the file `pactarawdata/scenario-sources/00Imported/WEO2022 extended data/WEO2022 extended data/raw_data_from_provider/used_in_pacta.scenario_preparation/IEA-EV-dataEV salesCarsProjection-APS.csv`

currently Line 2 ends with `,https://www.iea.org/reports/global-ev-outlook-2022/executive-summary`

for it to be a valid CSV, `,https://www.iea.org/reports/global-ev-outlook-2022/executive-summary` needs to be added to every line after that (L3:L49)

and technically the file should end with a new line

---

whether you want to modify the existing file in place, or create a new modified file and update [the config here](https://github.com/RMI-PACTA/workflow.scenario.preparation/blob/c7863274977493900860f3ae5dbf595bac505f02/config.yml#L45) I leave up to you

**Comment by cjyetman** [comment]
I suppose I could adapt the workflow here to read in plain text and then pass that on to pacta.scenario.data.prep to process. FYI though... Antoine added that string to Line 2, so it's not like it's truly a "raw" file.

**Comment by jdhoffa** [comment]
TBH, given that the column that we are concerned with was added manually to begin with, seems like it makes more sense just to fill it in properly... (or remove it entirely?)

**Comment by cjyetman** [comment]
will be resolved by:
- https://github.com/RMI-PACTA/pacta.scenario.data.preparation/pull/46
- https://github.com/RMI-PACTA/workflow.scenario.preparation/pull/49

**Comment by AlexAxthelm** [comment]
Closing, as I have altered the source file to include the column in all rows.
